### ISSUE TITLE
Close open windows when is program is shut down

### ISSUE THREAD

**Issue by nspruit** [AirWM/AirWM#39]
Pressing super+q shuts down the application, but the open windows still exist and it looks like the application still works (until you send it a new command of course).

**Comment by MartinRogalla** [comment]
Haha, this was actually pretty funny. I found how to do this finally. You can't use forEachWindow, since you change the object over which you are traversing. When closing 4 windows it would only close 2, since when it closed the first 2 it thought it had traversed the object since the current length of the object at that time was 2 and it traversed 2.

I'll clean up everything a bit and commit it in a moment.

**Comment by MartinRogalla** [comment]
Fixed in #43.

**Comment by MartinRogalla** [comment]
Fixed in #46.
